from enum import Enum


# Enum for Region Names
class Region(str, Enum):
    Africa: str = "Africa"
    America: str = "America"
    Antarctica: str = "Antarctica"
    Arctic: str = "Arctic"
    Asia: str = "Asia"
    Atlantic: str = "Atlantic"
    Australia: str = "Australia"
    Europe: str = "Europe"
    Indian: str = "Indian"
    Pacific: str = "Pacific"


RegionCountries: dict[Region, dict[str, str]] = {
    Region.Africa: {
        "Angola": "AO",
        "Burkina Faso": "BF",
        "Burundi": "BI",
        "Benin": "BJ",
        "Botswana": "BW",
        "Congo (Dem. Rep.)": "CD",
        "Central African Rep.": "CF",
        "Congo (Rep.)": "CG",
        "Côte d'Ivoire": "CI",
        "Cameroon": "CM",
        "Djibouti": "DJ",
        "Algeria": "DZ",
        "Egypt": "EG",
        "Western Sahara": "EH",
        "Eritrea": "ER",
        "Ethiopia": "ET",
        "Gabon": "GA",
        "Ghana": "GH",
        "Gambia": "GM",
        "Guinea": "GN",
        "Equatorial Guinea": "GQ",
        "Guinea-Bissau": "GW",
        "Kenya": "KE",
        "Liberia": "LR",
        "Lesotho": "LS",
        "Libya": "LY",
        "Morocco": "MA",
        "Mali": "ML",
        "Mauritania": "MR",
        "Malawi": "MW",
        "Mozambique": "MZ",
        "Namibia": "NA",
        "Niger": "NE",
        "Nigeria": "NG",
        "Rwanda": "RW",
        "Sudan": "SD",
        "Sierra Leone": "SL",
        "Senegal": "SN",
        "Somalia": "SO",
        "South Sudan": "SS",
        "Sao Tome & Principe": "ST",
        "Swaziland": "SZ",
        "Chad": "TD",
        "Togo": "TG",
        "Tunisia": "TN",
        "Tanzania": "TZ",
        "Uganda": "UG",
        "South Africa": "ZA",
        "Zambia": "ZM",
        "Zimbabwe": "ZW",
    },
    Region.America: {
        "Antigua & Barbuda": "AG",
        "Anguilla": "AI",
        "Argentina": "AR",
        "Aruba": "AW",
        "Barbados": "BB",
        "St Barthelemy": "BL",
        "Bolivia": "BO",
        "Caribbean NL": "BQ",
        "Brazil": "BR",
        "Bahamas": "BS",
        "Belize": "BZ",
        "Canada": "CA",
        "Chile": "CL",
        "Colombia": "CO",
        "Costa Rica": "CR",
        "Cuba": "CU",
        "Curaçao": "CW",
        "Dominica": "DM",
        "Dominican Republic": "DO",
        "Ecuador": "EC",
        "Grenada": "GD",
        "French Guiana": "GF",
        "Greenland": "GL",
        "Guadeloupe": "GP",
        "Guatemala": "GT",
        "Guyana": "GY",
        "Honduras": "HN",
        "Haiti": "HT",
        "Jamaica": "JM",
        "St Kitts & Nevis": "KN",
        "Cayman Islands": "KY",
        "St Lucia": "LC",
        "St Martin (French)": "MF",
        "Martinique": "MQ",
        "Montserrat": "MS",
        "Mexico": "MX",
        "Nicaragua": "NI",
        "Panama": "PA",
        "Peru": "PE",
        "St Pierre & Miquelon": "PM",
        "Puerto Rico": "PR",
        "Paraguay": "PY",
        "Suriname": "SR",
        "El Salvador": "SV",
        "St Maarten (Dutch)": "SX",
        "Turks & Caicos Is": "TC",
        "Trinidad & Tobago": "TT",
        "United States": "US",
        "Uruguay": "UY",
        "St Vincent": "VC",
        "Venezuela": "VE",
        "Virgin Islands (UK)": "VG",
        "Virgin Islands (US)": "VI",
    },
    Region.Antarctica: {"Antarctica": "AQ"},
    Region.Arctic: {"Svalbard & Jan Mayen": "SJ"},
    Region.Asia: {
        "United Arab Emirates": "AE",
        "Afghanistan": "AF",
        "Armenia": "AM",
        "Azerbaijan": "AZ",
        "Bangladesh": "BD",
        "Bahrain": "BH",
        "Brunei": "BN",
        "Bhutan": "BT",
        "China": "CN",
        "Cyprus": "CY",
        "Georgia": "GE",
        "Hong Kong": "HK",
        "Indonesia": "ID",
        "Israel": "IL",
        "India": "IN",
        "Iraq": "IQ",
        "Iran": "IR",
        "Jordan": "JO",
        "Japan": "JP",
        "Kyrgyzstan": "KG",
        "Cambodia": "KH",
        "Korea (North)": "KP",
        "Korea (South)": "KR",
        "Kuwait": "KW",
        "Kazakhstan": "KZ",
        "Laos": "LA",
        "Lebanon": "LB",
        "Sri Lanka": "LK",
        "Myanmar (Burma)": "MM",
        "Mongolia": "MN",
        "Macau": "MO",
        "Malaysia": "MY",
        "Nepal": "NP",
        "Oman": "OM",
        "Philippines": "PH",
        "Pakistan": "PK",
        "Palestine": "PS",
        "Qatar": "QA",
        "Saudi Arabia": "SA",
        "Singapore": "SG",
        "Syria": "SY",
        "Thailand": "TH",
        "Tajikistan": "TJ",
        "East Timor": "TL",
        "Turkmenistan": "TM",
        "Taiwan": "TW",
        "Uzbekistan": "UZ",
        "Vietnam": "VN",
        "Yemen": "YE",
    },
    Region.Atlantic: {
        "Bermuda": "BM",
        "Cape Verde": "CV",
        "Falkland Islands": "FK",
        "Faroe Islands": "FO",
        "South Georgia & the South Sandwich Islands": "GS",
        "Iceland": "IS",
        "St Helena": "SH",
    },
    Region.Australia: {"Australia": "AU"},
    Region.Europe: {
        "Unclassified": "UN",
        "Andorra": "AD",
        "Albania": "AL",
        "Austria": "AT",
        "Åland Islands": "AX",
        "Bosnia & Herzegovina": "BA",
        "Belgium": "BE",
        "Bulgaria": "BG",
        "Belarus": "BY",
        "Switzerland": "CH",
        "Czech Republic": "CZ",
        "Germany": "DE",
        "Denmark": "DK",
        "Estonia": "EE",
        "Spain": "ES",
        "Finland": "FI",
        "France": "FR",
        "Britain (UK)": "GB",
        "Guernsey": "GG",
        "Gibraltar": "GI",
        "Greece": "GR",
        "Croatia": "HR",
        "Hungary": "HU",
        "Ireland": "IE",
        "Isle of Man": "IM",
        "Italy": "IT",
        "Jersey": "JE",
        "Liechtenstein": "LI",
        "Lithuania": "LT",
        "Luxembourg": "LU",
        "Latvia": "LV",
        "Monaco": "MC",
        "Moldova": "MD",
        "Montenegro": "ME",
        "Macedonia": "MK",
        "Malta": "MT",
        "Netherlands": "NL",
        "Norway": "NO",
        "Poland": "PL",
        "Portugal": "PT",
        "Romania": "RO",
        "Serbia": "RS",
        "Russia": "RU",
        "Sweden": "SE",
        "Slovenia": "SI",
        "Slovakia": "SK",
        "San Marino": "SM",
        "Turkey": "TR",
        "Ukraine": "UA",
        "Vatican City": "VA",
    },
    Region.Indian: {
        "Cocos (Keeling) Islands": "CC",
        "Christmas Island": "CX",
        "British Indian Ocean Territory": "IO",
        "Comoros": "KM",
        "Madagascar": "MG",
        "Mauritius": "MU",
        "Maldives": "MV",
        "Réunion": "RE",
        "Seychelles": "SC",
        "French Southern & Antarctic Lands": "TF",
        "Mayotte": "YT",
    },
    Region.Pacific: {
        "Samoa (American)": "AS",
        "Cook Islands": "CK",
        "Fiji": "FJ",
        "Micronesia": "FM",
        "Guam": "GU",
        "Kiribati": "KI",
        "Marshall Islands": "MH",
        "Northern Mariana Islands": "MP",
        "New Caledonia": "NC",
        "Norfolk Island": "NF",
        "Nauru": "NR",
        "Niue": "NU",
        "New Zealand": "NZ",
        "French Polynesia": "PF",
        "Papua New Guinea": "PG",
        "Pitcairn": "PN",
        "Palau": "PW",
        "Solomon Islands": "SB",
        "Tokelau": "TK",
        "Tonga": "TO",
        "Tuvalu": "TV",
        "US minor outlying islands": "UM",
        "Vanuatu": "VU",
        "Wallis & Futuna": "WF",
        "Samoa (western)": "WS",
    },
}
